# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ilia/GPGPUTasks2023

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ilia/GPGPUTasks2023

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ilia/GPGPUTasks2023/CMakeFiles /home/ilia/GPGPUTasks2023//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ilia/GPGPUTasks2023/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named matrix_transpose

# Build rule for target.
matrix_transpose: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matrix_transpose
.PHONY : matrix_transpose

# fast build rule for target.
matrix_transpose/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_transpose.dir/build.make CMakeFiles/matrix_transpose.dir/build
.PHONY : matrix_transpose/fast

#=============================================================================
# Target rules for targets named matrix_multiplication

# Build rule for target.
matrix_multiplication: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matrix_multiplication
.PHONY : matrix_multiplication

# fast build rule for target.
matrix_multiplication/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_multiplication.dir/build.make CMakeFiles/matrix_multiplication.dir/build
.PHONY : matrix_multiplication/fast

#=============================================================================
# Target rules for targets named libclew

# Build rule for target.
libclew: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libclew
.PHONY : libclew

# fast build rule for target.
libclew/fast:
	$(MAKE) $(MAKESILENT) -f libs/clew/CMakeFiles/libclew.dir/build.make libs/clew/CMakeFiles/libclew.dir/build
.PHONY : libclew/fast

#=============================================================================
# Target rules for targets named libgpu

# Build rule for target.
libgpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libgpu
.PHONY : libgpu

# fast build rule for target.
libgpu/fast:
	$(MAKE) $(MAKESILENT) -f libs/gpu/CMakeFiles/libgpu.dir/build.make libs/gpu/CMakeFiles/libgpu.dir/build
.PHONY : libgpu/fast

#=============================================================================
# Target rules for targets named hexdumparray

# Build rule for target.
hexdumparray: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hexdumparray
.PHONY : hexdumparray

# fast build rule for target.
hexdumparray/fast:
	$(MAKE) $(MAKESILENT) -f libs/gpu/CMakeFiles/hexdumparray.dir/build.make libs/gpu/CMakeFiles/hexdumparray.dir/build
.PHONY : hexdumparray/fast

#=============================================================================
# Target rules for targets named libimages

# Build rule for target.
libimages: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libimages
.PHONY : libimages

# fast build rule for target.
libimages/fast:
	$(MAKE) $(MAKESILENT) -f libs/images/CMakeFiles/libimages.dir/build.make libs/images/CMakeFiles/libimages.dir/build
.PHONY : libimages/fast

#=============================================================================
# Target rules for targets named libutils

# Build rule for target.
libutils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libutils
.PHONY : libutils

# fast build rule for target.
libutils/fast:
	$(MAKE) $(MAKESILENT) -f libs/utils/CMakeFiles/libutils.dir/build.make libs/utils/CMakeFiles/libutils.dir/build
.PHONY : libutils/fast

src/main_matrix_multiplication.o: src/main_matrix_multiplication.cpp.o
.PHONY : src/main_matrix_multiplication.o

# target to build an object file
src/main_matrix_multiplication.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_multiplication.dir/build.make CMakeFiles/matrix_multiplication.dir/src/main_matrix_multiplication.cpp.o
.PHONY : src/main_matrix_multiplication.cpp.o

src/main_matrix_multiplication.i: src/main_matrix_multiplication.cpp.i
.PHONY : src/main_matrix_multiplication.i

# target to preprocess a source file
src/main_matrix_multiplication.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_multiplication.dir/build.make CMakeFiles/matrix_multiplication.dir/src/main_matrix_multiplication.cpp.i
.PHONY : src/main_matrix_multiplication.cpp.i

src/main_matrix_multiplication.s: src/main_matrix_multiplication.cpp.s
.PHONY : src/main_matrix_multiplication.s

# target to generate assembly for a file
src/main_matrix_multiplication.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_multiplication.dir/build.make CMakeFiles/matrix_multiplication.dir/src/main_matrix_multiplication.cpp.s
.PHONY : src/main_matrix_multiplication.cpp.s

src/main_matrix_transpose.o: src/main_matrix_transpose.cpp.o
.PHONY : src/main_matrix_transpose.o

# target to build an object file
src/main_matrix_transpose.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_transpose.dir/build.make CMakeFiles/matrix_transpose.dir/src/main_matrix_transpose.cpp.o
.PHONY : src/main_matrix_transpose.cpp.o

src/main_matrix_transpose.i: src/main_matrix_transpose.cpp.i
.PHONY : src/main_matrix_transpose.i

# target to preprocess a source file
src/main_matrix_transpose.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_transpose.dir/build.make CMakeFiles/matrix_transpose.dir/src/main_matrix_transpose.cpp.i
.PHONY : src/main_matrix_transpose.cpp.i

src/main_matrix_transpose.s: src/main_matrix_transpose.cpp.s
.PHONY : src/main_matrix_transpose.s

# target to generate assembly for a file
src/main_matrix_transpose.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_transpose.dir/build.make CMakeFiles/matrix_transpose.dir/src/main_matrix_transpose.cpp.s
.PHONY : src/main_matrix_transpose.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hexdumparray"
	@echo "... libclew"
	@echo "... libgpu"
	@echo "... libimages"
	@echo "... libutils"
	@echo "... matrix_multiplication"
	@echo "... matrix_transpose"
	@echo "... src/main_matrix_multiplication.o"
	@echo "... src/main_matrix_multiplication.i"
	@echo "... src/main_matrix_multiplication.s"
	@echo "... src/main_matrix_transpose.o"
	@echo "... src/main_matrix_transpose.i"
	@echo "... src/main_matrix_transpose.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

